// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/proto/examplepb/a_bit_of_everything.proto

package examplepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import sub "github.com/grpc-ecosystem/grpc-gateway/examples/proto/sub"
import sub2 "github.com/grpc-ecosystem/grpc-gateway/examples/proto/sub2"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// NumericEnum is one or zero.
type NumericEnum int32

const (
	// ZERO means 0
	NumericEnum_ZERO NumericEnum = 0
	// ONE means 1
	NumericEnum_ONE NumericEnum = 1
)

var NumericEnum_name = map[int32]string{
	0: "ZERO",
	1: "ONE",
}
var NumericEnum_value = map[string]int32{
	"ZERO": 0,
	"ONE":  1,
}

func (x NumericEnum) String() string {
	return proto.EnumName(NumericEnum_name, int32(x))
}
func (NumericEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_a0cdfe3e1bdeb13b, []int{0}
}

// DeepEnum is one or zero.
type ABitOfEverything_Nested_DeepEnum int32

const (
	// FALSE is false.
	ABitOfEverything_Nested_FALSE ABitOfEverything_Nested_DeepEnum = 0
	// TRUE is true.
	ABitOfEverything_Nested_TRUE ABitOfEverything_Nested_DeepEnum = 1
)

var ABitOfEverything_Nested_DeepEnum_name = map[int32]string{
	0: "FALSE",
	1: "TRUE",
}
var ABitOfEverything_Nested_DeepEnum_value = map[string]int32{
	"FALSE": 0,
	"TRUE":  1,
}

func (x ABitOfEverything_Nested_DeepEnum) String() string {
	return proto.EnumName(ABitOfEverything_Nested_DeepEnum_name, int32(x))
}
func (ABitOfEverything_Nested_DeepEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_a0cdfe3e1bdeb13b, []int{0, 0, 0}
}

type MimicObjectResponse_MimicResponseEnum int32

const (
	MimicObjectResponse_VALUE_ONE MimicObjectResponse_MimicResponseEnum = 0
	MimicObjectResponse_VALUE_TWO MimicObjectResponse_MimicResponseEnum = 1
)

var MimicObjectResponse_MimicResponseEnum_name = map[int32]string{
	0: "VALUE_ONE",
	1: "VALUE_TWO",
}
var MimicObjectResponse_MimicResponseEnum_value = map[string]int32{
	"VALUE_ONE": 0,
	"VALUE_TWO": 1,
}

func (x MimicObjectResponse_MimicResponseEnum) String() string {
	return proto.EnumName(MimicObjectResponse_MimicResponseEnum_name, int32(x))
}
func (MimicObjectResponse_MimicResponseEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_a0cdfe3e1bdeb13b, []int{3, 0}
}

type MimicObjectRequest_MimicRequestEnum int32

const (
	MimicObjectRequest_VALUE_ONE MimicObjectRequest_MimicRequestEnum = 0
	MimicObjectRequest_VALUE_TWO MimicObjectRequest_MimicRequestEnum = 1
)

var MimicObjectRequest_MimicRequestEnum_name = map[int32]string{
	0: "VALUE_ONE",
	1: "VALUE_TWO",
}
var MimicObjectRequest_MimicRequestEnum_value = map[string]int32{
	"VALUE_ONE": 0,
	"VALUE_TWO": 1,
}

func (x MimicObjectRequest_MimicRequestEnum) String() string {
	return proto.EnumName(MimicObjectRequest_MimicRequestEnum_name, int32(x))
}
func (MimicObjectRequest_MimicRequestEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_a0cdfe3e1bdeb13b, []int{4, 0}
}

type MimicObjectHidden_HiddenEnum int32

const (
	MimicObjectHidden_VALUE_ONE MimicObjectHidden_HiddenEnum = 0
	MimicObjectHidden_VALUE_TWO MimicObjectHidden_HiddenEnum = 1
)

var MimicObjectHidden_HiddenEnum_name = map[int32]string{
	0: "VALUE_ONE",
	1: "VALUE_TWO",
}
var MimicObjectHidden_HiddenEnum_value = map[string]int32{
	"VALUE_ONE": 0,
	"VALUE_TWO": 1,
}

func (x MimicObjectHidden_HiddenEnum) String() string {
	return proto.EnumName(MimicObjectHidden_HiddenEnum_name, int32(x))
}
func (MimicObjectHidden_HiddenEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_a0cdfe3e1bdeb13b, []int{5, 0}
}

// Intentionaly complicated message type to cover many features of Protobuf.
// NEXT ID: 30
type ABitOfEverything struct {
	SingleNested        *ABitOfEverything_Nested   `protobuf:"bytes,25,opt,name=single_nested,json=singleNested,proto3" json:"single_nested,omitempty"`
	Uuid                string                     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Nested              []*ABitOfEverything_Nested `protobuf:"bytes,2,rep,name=nested,proto3" json:"nested,omitempty"`
	FloatValue          float32                    `protobuf:"fixed32,3,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	DoubleValue         float64                    `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	Int64Value          int64                      `protobuf:"varint,5,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Uint64Value         uint64                     `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	Int32Value          int32                      `protobuf:"varint,7,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Fixed64Value        uint64                     `protobuf:"fixed64,8,opt,name=fixed64_value,json=fixed64Value,proto3" json:"fixed64_value,omitempty"`
	Fixed32Value        uint32                     `protobuf:"fixed32,9,opt,name=fixed32_value,json=fixed32Value,proto3" json:"fixed32_value,omitempty"`
	BoolValue           bool                       `protobuf:"varint,10,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	StringValue         string                     `protobuf:"bytes,11,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BytesValue          []byte                     `protobuf:"bytes,29,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	Uint32Value         uint32                     `protobuf:"varint,13,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	EnumValue           NumericEnum                `protobuf:"varint,14,opt,name=enum_value,json=enumValue,proto3,enum=grpc.gateway.examples.examplepb.NumericEnum" json:"enum_value,omitempty"`
	Sfixed32Value       int32                      `protobuf:"fixed32,15,opt,name=sfixed32_value,json=sfixed32Value,proto3" json:"sfixed32_value,omitempty"`
	Sfixed64Value       int64                      `protobuf:"fixed64,16,opt,name=sfixed64_value,json=sfixed64Value,proto3" json:"sfixed64_value,omitempty"`
	Sint32Value         int32                      `protobuf:"zigzag32,17,opt,name=sint32_value,json=sint32Value,proto3" json:"sint32_value,omitempty"`
	Sint64Value         int64                      `protobuf:"zigzag64,18,opt,name=sint64_value,json=sint64Value,proto3" json:"sint64_value,omitempty"`
	RepeatedStringValue []string                   `protobuf:"bytes,19,rep,name=repeated_string_value,json=repeatedStringValue,proto3" json:"repeated_string_value,omitempty"`
	// Types that are valid to be assigned to OneofValue:
	//	*ABitOfEverything_OneofEmpty
	//	*ABitOfEverything_OneofString
	OneofValue               isABitOfEverything_OneofValue       `protobuf_oneof:"oneof_value"`
	MapValue                 map[string]NumericEnum              `protobuf:"bytes,22,rep,name=map_value,json=mapValue,proto3" json:"map_value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=grpc.gateway.examples.examplepb.NumericEnum"`
	MappedStringValue        map[string]string                   `protobuf:"bytes,23,rep,name=mapped_string_value,json=mappedStringValue,proto3" json:"mapped_string_value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MappedNestedValue        map[string]*ABitOfEverything_Nested `protobuf:"bytes,24,rep,name=mapped_nested_value,json=mappedNestedValue,proto3" json:"mapped_nested_value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	NonConventionalNameValue string                              `protobuf:"bytes,26,opt,name=nonConventionalNameValue,proto3" json:"nonConventionalNameValue,omitempty"`
	TimestampValue           *timestamp.Timestamp                `protobuf:"bytes,27,opt,name=timestamp_value,json=timestampValue,proto3" json:"timestamp_value,omitempty"`
	// repeated enum value. it is comma-separated in query
	RepeatedEnumValue []NumericEnum `protobuf:"varint,28,rep,packed,name=repeated_enum_value,json=repeatedEnumValue,proto3,enum=grpc.gateway.examples.examplepb.NumericEnum" json:"repeated_enum_value,omitempty"`
	// This comment will not appear, MimicObject description will be used instead.
	MimicString          *MimicObjectHidden `protobuf:"bytes,30,opt,name=mimic_string,json=mimicString,proto3" json:"mimic_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ABitOfEverything) Reset()         { *m = ABitOfEverything{} }
func (m *ABitOfEverything) String() string { return proto.CompactTextString(m) }
func (*ABitOfEverything) ProtoMessage()    {}
func (*ABitOfEverything) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_a0cdfe3e1bdeb13b, []int{0}
}
func (m *ABitOfEverything) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ABitOfEverything.Unmarshal(m, b)
}
func (m *ABitOfEverything) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ABitOfEverything.Marshal(b, m, deterministic)
}
func (dst *ABitOfEverything) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ABitOfEverything.Merge(dst, src)
}
func (m *ABitOfEverything) XXX_Size() int {
	return xxx_messageInfo_ABitOfEverything.Size(m)
}
func (m *ABitOfEverything) XXX_DiscardUnknown() {
	xxx_messageInfo_ABitOfEverything.DiscardUnknown(m)
}

var xxx_messageInfo_ABitOfEverything proto.InternalMessageInfo

func (m *ABitOfEverything) GetSingleNested() *ABitOfEverything_Nested {
	if m != nil {
		return m.SingleNested
	}
	return nil
}

func (m *ABitOfEverything) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ABitOfEverything) GetNested() []*ABitOfEverything_Nested {
	if m != nil {
		return m.Nested
	}
	return nil
}

func (m *ABitOfEverything) GetFloatValue() float32 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *ABitOfEverything) GetDoubleValue() float64 {
	if m != nil {
		return m.DoubleValue
	}
	return 0
}

func (m *ABitOfEverything) GetInt64Value() int64 {
	if m != nil {
		return m.Int64Value
	}
	return 0
}

func (m *ABitOfEverything) GetUint64Value() uint64 {
	if m != nil {
		return m.Uint64Value
	}
	return 0
}

func (m *ABitOfEverything) GetInt32Value() int32 {
	if m != nil {
		return m.Int32Value
	}
	return 0
}

func (m *ABitOfEverything) GetFixed64Value() uint64 {
	if m != nil {
		return m.Fixed64Value
	}
	return 0
}

func (m *ABitOfEverything) GetFixed32Value() uint32 {
	if m != nil {
		return m.Fixed32Value
	}
	return 0
}

func (m *ABitOfEverything) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *ABitOfEverything) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *ABitOfEverything) GetBytesValue() []byte {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

func (m *ABitOfEverything) GetUint32Value() uint32 {
	if m != nil {
		return m.Uint32Value
	}
	return 0
}

func (m *ABitOfEverything) GetEnumValue() NumericEnum {
	if m != nil {
		return m.EnumValue
	}
	return NumericEnum_ZERO
}

func (m *ABitOfEverything) GetSfixed32Value() int32 {
	if m != nil {
		return m.Sfixed32Value
	}
	return 0
}

func (m *ABitOfEverything) GetSfixed64Value() int64 {
	if m != nil {
		return m.Sfixed64Value
	}
	return 0
}

func (m *ABitOfEverything) GetSint32Value() int32 {
	if m != nil {
		return m.Sint32Value
	}
	return 0
}

func (m *ABitOfEverything) GetSint64Value() int64 {
	if m != nil {
		return m.Sint64Value
	}
	return 0
}

func (m *ABitOfEverything) GetRepeatedStringValue() []string {
	if m != nil {
		return m.RepeatedStringValue
	}
	return nil
}

type isABitOfEverything_OneofValue interface {
	isABitOfEverything_OneofValue()
}

type ABitOfEverything_OneofEmpty struct {
	OneofEmpty *empty.Empty `protobuf:"bytes,20,opt,name=oneof_empty,json=oneofEmpty,proto3,oneof"`
}

type ABitOfEverything_OneofString struct {
	OneofString string `protobuf:"bytes,21,opt,name=oneof_string,json=oneofString,proto3,oneof"`
}

func (*ABitOfEverything_OneofEmpty) isABitOfEverything_OneofValue() {}

func (*ABitOfEverything_OneofString) isABitOfEverything_OneofValue() {}

func (m *ABitOfEverything) GetOneofValue() isABitOfEverything_OneofValue {
	if m != nil {
		return m.OneofValue
	}
	return nil
}

func (m *ABitOfEverything) GetOneofEmpty() *empty.Empty {
	if x, ok := m.GetOneofValue().(*ABitOfEverything_OneofEmpty); ok {
		return x.OneofEmpty
	}
	return nil
}

func (m *ABitOfEverything) GetOneofString() string {
	if x, ok := m.GetOneofValue().(*ABitOfEverything_OneofString); ok {
		return x.OneofString
	}
	return ""
}

func (m *ABitOfEverything) GetMapValue() map[string]NumericEnum {
	if m != nil {
		return m.MapValue
	}
	return nil
}

func (m *ABitOfEverything) GetMappedStringValue() map[string]string {
	if m != nil {
		return m.MappedStringValue
	}
	return nil
}

func (m *ABitOfEverything) GetMappedNestedValue() map[string]*ABitOfEverything_Nested {
	if m != nil {
		return m.MappedNestedValue
	}
	return nil
}

func (m *ABitOfEverything) GetNonConventionalNameValue() string {
	if m != nil {
		return m.NonConventionalNameValue
	}
	return ""
}

func (m *ABitOfEverything) GetTimestampValue() *timestamp.Timestamp {
	if m != nil {
		return m.TimestampValue
	}
	return nil
}

func (m *ABitOfEverything) GetRepeatedEnumValue() []NumericEnum {
	if m != nil {
		return m.RepeatedEnumValue
	}
	return nil
}

func (m *ABitOfEverything) GetMimicString() *MimicObjectHidden {
	if m != nil {
		return m.MimicString
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ABitOfEverything) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ABitOfEverything_OneofMarshaler, _ABitOfEverything_OneofUnmarshaler, _ABitOfEverything_OneofSizer, []interface{}{
		(*ABitOfEverything_OneofEmpty)(nil),
		(*ABitOfEverything_OneofString)(nil),
	}
}

func _ABitOfEverything_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ABitOfEverything)
	// oneof_value
	switch x := m.OneofValue.(type) {
	case *ABitOfEverything_OneofEmpty:
		b.EncodeVarint(20<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OneofEmpty); err != nil {
			return err
		}
	case *ABitOfEverything_OneofString:
		b.EncodeVarint(21<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.OneofString)
	case nil:
	default:
		return fmt.Errorf("ABitOfEverything.OneofValue has unexpected type %T", x)
	}
	return nil
}

func _ABitOfEverything_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ABitOfEverything)
	switch tag {
	case 20: // oneof_value.oneof_empty
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(empty.Empty)
		err := b.DecodeMessage(msg)
		m.OneofValue = &ABitOfEverything_OneofEmpty{msg}
		return true, err
	case 21: // oneof_value.oneof_string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OneofValue = &ABitOfEverything_OneofString{x}
		return true, err
	default:
		return false, nil
	}
}

func _ABitOfEverything_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ABitOfEverything)
	// oneof_value
	switch x := m.OneofValue.(type) {
	case *ABitOfEverything_OneofEmpty:
		s := proto.Size(x.OneofEmpty)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ABitOfEverything_OneofString:
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(len(x.OneofString)))
		n += len(x.OneofString)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Nested is nested type.
type ABitOfEverything_Nested struct {
	// name is nested field.
	Name                 string                           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount               uint32                           `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Ok                   ABitOfEverything_Nested_DeepEnum `protobuf:"varint,3,opt,name=ok,proto3,enum=grpc.gateway.examples.examplepb.ABitOfEverything_Nested_DeepEnum" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ABitOfEverything_Nested) Reset()         { *m = ABitOfEverything_Nested{} }
func (m *ABitOfEverything_Nested) String() string { return proto.CompactTextString(m) }
func (*ABitOfEverything_Nested) ProtoMessage()    {}
func (*ABitOfEverything_Nested) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_a0cdfe3e1bdeb13b, []int{0, 0}
}
func (m *ABitOfEverything_Nested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ABitOfEverything_Nested.Unmarshal(m, b)
}
func (m *ABitOfEverything_Nested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ABitOfEverything_Nested.Marshal(b, m, deterministic)
}
func (dst *ABitOfEverything_Nested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ABitOfEverything_Nested.Merge(dst, src)
}
func (m *ABitOfEverything_Nested) XXX_Size() int {
	return xxx_messageInfo_ABitOfEverything_Nested.Size(m)
}
func (m *ABitOfEverything_Nested) XXX_DiscardUnknown() {
	xxx_messageInfo_ABitOfEverything_Nested.DiscardUnknown(m)
}

var xxx_messageInfo_ABitOfEverything_Nested proto.InternalMessageInfo

func (m *ABitOfEverything_Nested) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ABitOfEverything_Nested) GetAmount() uint32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ABitOfEverything_Nested) GetOk() ABitOfEverything_Nested_DeepEnum {
	if m != nil {
		return m.Ok
	}
	return ABitOfEverything_Nested_FALSE
}

type Body struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_a0cdfe3e1bdeb13b, []int{1}
}
func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (dst *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(dst, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MessageWithBody struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 *Body    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageWithBody) Reset()         { *m = MessageWithBody{} }
func (m *MessageWithBody) String() string { return proto.CompactTextString(m) }
func (*MessageWithBody) ProtoMessage()    {}
func (*MessageWithBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_a0cdfe3e1bdeb13b, []int{2}
}
func (m *MessageWithBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithBody.Unmarshal(m, b)
}
func (m *MessageWithBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithBody.Marshal(b, m, deterministic)
}
func (dst *MessageWithBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithBody.Merge(dst, src)
}
func (m *MessageWithBody) XXX_Size() int {
	return xxx_messageInfo_MessageWithBody.Size(m)
}
func (m *MessageWithBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithBody.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithBody proto.InternalMessageInfo

func (m *MessageWithBody) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageWithBody) GetData() *Body {
	if m != nil {
		return m.Data
	}
	return nil
}

type MimicObjectResponse struct {
	ResponseValueOne     string                                `protobuf:"bytes,1,opt,name=response_value_one,json=responseValueOne,proto3" json:"response_value_one,omitempty"`
	ResponseValueTwo     string                                `protobuf:"bytes,2,opt,name=response_value_two,json=responseValueTwo,proto3" json:"response_value_two,omitempty"`
	ResponseEnum         MimicObjectResponse_MimicResponseEnum `protobuf:"varint,3,opt,name=response_enum,json=responseEnum,proto3,enum=grpc.gateway.examples.examplepb.MimicObjectResponse_MimicResponseEnum" json:"response_enum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *MimicObjectResponse) Reset()         { *m = MimicObjectResponse{} }
func (m *MimicObjectResponse) String() string { return proto.CompactTextString(m) }
func (*MimicObjectResponse) ProtoMessage()    {}
func (*MimicObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_a0cdfe3e1bdeb13b, []int{3}
}
func (m *MimicObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MimicObjectResponse.Unmarshal(m, b)
}
func (m *MimicObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MimicObjectResponse.Marshal(b, m, deterministic)
}
func (dst *MimicObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MimicObjectResponse.Merge(dst, src)
}
func (m *MimicObjectResponse) XXX_Size() int {
	return xxx_messageInfo_MimicObjectResponse.Size(m)
}
func (m *MimicObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MimicObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MimicObjectResponse proto.InternalMessageInfo

func (m *MimicObjectResponse) GetResponseValueOne() string {
	if m != nil {
		return m.ResponseValueOne
	}
	return ""
}

func (m *MimicObjectResponse) GetResponseValueTwo() string {
	if m != nil {
		return m.ResponseValueTwo
	}
	return ""
}

func (m *MimicObjectResponse) GetResponseEnum() MimicObjectResponse_MimicResponseEnum {
	if m != nil {
		return m.ResponseEnum
	}
	return MimicObjectResponse_VALUE_ONE
}

type MimicObjectRequest struct {
	RequestValueOne      string                              `protobuf:"bytes,1,opt,name=request_value_one,json=requestValueOne,proto3" json:"request_value_one,omitempty"`
	RequestValueTwo      string                              `protobuf:"bytes,2,opt,name=request_value_two,json=requestValueTwo,proto3" json:"request_value_two,omitempty"`
	RequestEnum          MimicObjectRequest_MimicRequestEnum `protobuf:"varint,3,opt,name=request_enum,json=requestEnum,proto3,enum=grpc.gateway.examples.examplepb.MimicObjectRequest_MimicRequestEnum" json:"request_enum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *MimicObjectRequest) Reset()         { *m = MimicObjectRequest{} }
func (m *MimicObjectRequest) String() string { return proto.CompactTextString(m) }
func (*MimicObjectRequest) ProtoMessage()    {}
func (*MimicObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_a0cdfe3e1bdeb13b, []int{4}
}
func (m *MimicObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MimicObjectRequest.Unmarshal(m, b)
}
func (m *MimicObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MimicObjectRequest.Marshal(b, m, deterministic)
}
func (dst *MimicObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MimicObjectRequest.Merge(dst, src)
}
func (m *MimicObjectRequest) XXX_Size() int {
	return xxx_messageInfo_MimicObjectRequest.Size(m)
}
func (m *MimicObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MimicObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MimicObjectRequest proto.InternalMessageInfo

func (m *MimicObjectRequest) GetRequestValueOne() string {
	if m != nil {
		return m.RequestValueOne
	}
	return ""
}

func (m *MimicObjectRequest) GetRequestValueTwo() string {
	if m != nil {
		return m.RequestValueTwo
	}
	return ""
}

func (m *MimicObjectRequest) GetRequestEnum() MimicObjectRequest_MimicRequestEnum {
	if m != nil {
		return m.RequestEnum
	}
	return MimicObjectRequest_VALUE_ONE
}

type MimicObjectHidden struct {
	HiddenValueOne       string                       `protobuf:"bytes,1,opt,name=hidden_value_one,json=hiddenValueOne,proto3" json:"hidden_value_one,omitempty"`
	HiddenValueTwo       string                       `protobuf:"bytes,2,opt,name=hidden_value_two,json=hiddenValueTwo,proto3" json:"hidden_value_two,omitempty"`
	HiddenEnum           MimicObjectHidden_HiddenEnum `protobuf:"varint,3,opt,name=hidden_enum,json=hiddenEnum,proto3,enum=grpc.gateway.examples.examplepb.MimicObjectHidden_HiddenEnum" json:"hidden_enum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *MimicObjectHidden) Reset()         { *m = MimicObjectHidden{} }
func (m *MimicObjectHidden) String() string { return proto.CompactTextString(m) }
func (*MimicObjectHidden) ProtoMessage()    {}
func (*MimicObjectHidden) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_bit_of_everything_a0cdfe3e1bdeb13b, []int{5}
}
func (m *MimicObjectHidden) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MimicObjectHidden.Unmarshal(m, b)
}
func (m *MimicObjectHidden) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MimicObjectHidden.Marshal(b, m, deterministic)
}
func (dst *MimicObjectHidden) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MimicObjectHidden.Merge(dst, src)
}
func (m *MimicObjectHidden) XXX_Size() int {
	return xxx_messageInfo_MimicObjectHidden.Size(m)
}
func (m *MimicObjectHidden) XXX_DiscardUnknown() {
	xxx_messageInfo_MimicObjectHidden.DiscardUnknown(m)
}

var xxx_messageInfo_MimicObjectHidden proto.InternalMessageInfo

func (m *MimicObjectHidden) GetHiddenValueOne() string {
	if m != nil {
		return m.HiddenValueOne
	}
	return ""
}

func (m *MimicObjectHidden) GetHiddenValueTwo() string {
	if m != nil {
		return m.HiddenValueTwo
	}
	return ""
}

func (m *MimicObjectHidden) GetHiddenEnum() MimicObjectHidden_HiddenEnum {
	if m != nil {
		return m.HiddenEnum
	}
	return MimicObjectHidden_VALUE_ONE
}

func init() {
	proto.RegisterType((*ABitOfEverything)(nil), "grpc.gateway.examples.examplepb.ABitOfEverything")
	proto.RegisterMapType((map[string]NumericEnum)(nil), "grpc.gateway.examples.examplepb.ABitOfEverything.MapValueEntry")
	proto.RegisterMapType((map[string]*ABitOfEverything_Nested)(nil), "grpc.gateway.examples.examplepb.ABitOfEverything.MappedNestedValueEntry")
	proto.RegisterMapType((map[string]string)(nil), "grpc.gateway.examples.examplepb.ABitOfEverything.MappedStringValueEntry")
	proto.RegisterType((*ABitOfEverything_Nested)(nil), "grpc.gateway.examples.examplepb.ABitOfEverything.Nested")
	proto.RegisterType((*Body)(nil), "grpc.gateway.examples.examplepb.Body")
	proto.RegisterType((*MessageWithBody)(nil), "grpc.gateway.examples.examplepb.MessageWithBody")
	proto.RegisterType((*MimicObjectResponse)(nil), "grpc.gateway.examples.examplepb.MimicObjectResponse")
	proto.RegisterType((*MimicObjectRequest)(nil), "grpc.gateway.examples.examplepb.MimicObjectRequest")
	proto.RegisterType((*MimicObjectHidden)(nil), "grpc.gateway.examples.examplepb.MimicObjectHidden")
	proto.RegisterEnum("grpc.gateway.examples.examplepb.NumericEnum", NumericEnum_name, NumericEnum_value)
	proto.RegisterEnum("grpc.gateway.examples.examplepb.ABitOfEverything_Nested_DeepEnum", ABitOfEverything_Nested_DeepEnum_name, ABitOfEverything_Nested_DeepEnum_value)
	proto.RegisterEnum("grpc.gateway.examples.examplepb.MimicObjectResponse_MimicResponseEnum", MimicObjectResponse_MimicResponseEnum_name, MimicObjectResponse_MimicResponseEnum_value)
	proto.RegisterEnum("grpc.gateway.examples.examplepb.MimicObjectRequest_MimicRequestEnum", MimicObjectRequest_MimicRequestEnum_name, MimicObjectRequest_MimicRequestEnum_value)
	proto.RegisterEnum("grpc.gateway.examples.examplepb.MimicObjectHidden_HiddenEnum", MimicObjectHidden_HiddenEnum_name, MimicObjectHidden_HiddenEnum_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ABitOfEverythingServiceClient is the client API for ABitOfEverythingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ABitOfEverythingServiceClient interface {
	// Create a new ABitOfEverything
	//
	// This API creates a new ABitOfEverything
	Create(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	CreateBody(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	Lookup(ctx context.Context, in *sub2.IdMessage, opts ...grpc.CallOption) (*ABitOfEverything, error)
	Update(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *sub2.IdMessage, opts ...grpc.CallOption) (*empty.Empty, error)
	GetQuery(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*empty.Empty, error)
	// Echo allows posting a StringMessage value.
	//
	// It also exposes multiple bindings.
	//
	// This makes it useful when validating that the OpenAPI v2 API
	// description exposes documentation correctly on all paths
	// defined as additional_bindings in the proto.
	Echo(ctx context.Context, in *sub.StringMessage, opts ...grpc.CallOption) (*sub.StringMessage, error)
	DeepPathEcho(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	NoBindings(ctx context.Context, in *duration.Duration, opts ...grpc.CallOption) (*empty.Empty, error)
	Timeout(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	ErrorWithDetails(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	GetMessageWithBody(ctx context.Context, in *MessageWithBody, opts ...grpc.CallOption) (*empty.Empty, error)
	PostWithEmptyBody(ctx context.Context, in *Body, opts ...grpc.CallOption) (*empty.Empty, error)
	GetWithMimicObjectResponse(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MimicObjectResponse, error)
	PostWithMimicObjectRequest(ctx context.Context, in *MimicObjectRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type aBitOfEverythingServiceClient struct {
	cc *grpc.ClientConn
}

func NewABitOfEverythingServiceClient(cc *grpc.ClientConn) ABitOfEverythingServiceClient {
	return &aBitOfEverythingServiceClient{cc}
}

func (c *aBitOfEverythingServiceClient) Create(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) CreateBody(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/CreateBody", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Lookup(ctx context.Context, in *sub2.IdMessage, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Lookup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Update(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Delete(ctx context.Context, in *sub2.IdMessage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) GetQuery(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/GetQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Echo(ctx context.Context, in *sub.StringMessage, opts ...grpc.CallOption) (*sub.StringMessage, error) {
	out := new(sub.StringMessage)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) DeepPathEcho(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/DeepPathEcho", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) NoBindings(ctx context.Context, in *duration.Duration, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/NoBindings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Timeout(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Timeout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) ErrorWithDetails(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/ErrorWithDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) GetMessageWithBody(ctx context.Context, in *MessageWithBody, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/GetMessageWithBody", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) PostWithEmptyBody(ctx context.Context, in *Body, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/PostWithEmptyBody", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) GetWithMimicObjectResponse(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MimicObjectResponse, error) {
	out := new(MimicObjectResponse)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/GetWithMimicObjectResponse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) PostWithMimicObjectRequest(ctx context.Context, in *MimicObjectRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.ABitOfEverythingService/PostWithMimicObjectRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ABitOfEverythingServiceServer is the server API for ABitOfEverythingService service.
type ABitOfEverythingServiceServer interface {
	// Create a new ABitOfEverything
	//
	// This API creates a new ABitOfEverything
	Create(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	CreateBody(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	Lookup(context.Context, *sub2.IdMessage) (*ABitOfEverything, error)
	Update(context.Context, *ABitOfEverything) (*empty.Empty, error)
	Delete(context.Context, *sub2.IdMessage) (*empty.Empty, error)
	GetQuery(context.Context, *ABitOfEverything) (*empty.Empty, error)
	// Echo allows posting a StringMessage value.
	//
	// It also exposes multiple bindings.
	//
	// This makes it useful when validating that the OpenAPI v2 API
	// description exposes documentation correctly on all paths
	// defined as additional_bindings in the proto.
	Echo(context.Context, *sub.StringMessage) (*sub.StringMessage, error)
	DeepPathEcho(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	NoBindings(context.Context, *duration.Duration) (*empty.Empty, error)
	Timeout(context.Context, *empty.Empty) (*empty.Empty, error)
	ErrorWithDetails(context.Context, *empty.Empty) (*empty.Empty, error)
	GetMessageWithBody(context.Context, *MessageWithBody) (*empty.Empty, error)
	PostWithEmptyBody(context.Context, *Body) (*empty.Empty, error)
	GetWithMimicObjectResponse(context.Context, *empty.Empty) (*MimicObjectResponse, error)
	PostWithMimicObjectRequest(context.Context, *MimicObjectRequest) (*empty.Empty, error)
}

func RegisterABitOfEverythingServiceServer(s *grpc.Server, srv ABitOfEverythingServiceServer) {
	s.RegisterService(&_ABitOfEverythingService_serviceDesc, srv)
}

func _ABitOfEverythingService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Create(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_CreateBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).CreateBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/CreateBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).CreateBody(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(sub2.IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Lookup(ctx, req.(*sub2.IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Update(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(sub2.IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Delete(ctx, req.(*sub2.IdMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_GetQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).GetQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/GetQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).GetQuery(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(sub.StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Echo(ctx, req.(*sub.StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_DeepPathEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).DeepPathEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/DeepPathEcho",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).DeepPathEcho(ctx, req.(*ABitOfEverything))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_NoBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(duration.Duration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).NoBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/NoBindings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).NoBindings(ctx, req.(*duration.Duration))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_Timeout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).Timeout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/Timeout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).Timeout(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_ErrorWithDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).ErrorWithDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/ErrorWithDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).ErrorWithDetails(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_GetMessageWithBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageWithBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).GetMessageWithBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/GetMessageWithBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).GetMessageWithBody(ctx, req.(*MessageWithBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_PostWithEmptyBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Body)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).PostWithEmptyBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/PostWithEmptyBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).PostWithEmptyBody(ctx, req.(*Body))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_GetWithMimicObjectResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).GetWithMimicObjectResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/GetWithMimicObjectResponse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).GetWithMimicObjectResponse(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ABitOfEverythingService_PostWithMimicObjectRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MimicObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ABitOfEverythingServiceServer).PostWithMimicObjectRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.ABitOfEverythingService/PostWithMimicObjectRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ABitOfEverythingServiceServer).PostWithMimicObjectRequest(ctx, req.(*MimicObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ABitOfEverythingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gateway.examples.examplepb.ABitOfEverythingService",
	HandlerType: (*ABitOfEverythingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ABitOfEverythingService_Create_Handler,
		},
		{
			MethodName: "CreateBody",
			Handler:    _ABitOfEverythingService_CreateBody_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _ABitOfEverythingService_Lookup_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ABitOfEverythingService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ABitOfEverythingService_Delete_Handler,
		},
		{
			MethodName: "GetQuery",
			Handler:    _ABitOfEverythingService_GetQuery_Handler,
		},
		{
			MethodName: "Echo",
			Handler:    _ABitOfEverythingService_Echo_Handler,
		},
		{
			MethodName: "DeepPathEcho",
			Handler:    _ABitOfEverythingService_DeepPathEcho_Handler,
		},
		{
			MethodName: "NoBindings",
			Handler:    _ABitOfEverythingService_NoBindings_Handler,
		},
		{
			MethodName: "Timeout",
			Handler:    _ABitOfEverythingService_Timeout_Handler,
		},
		{
			MethodName: "ErrorWithDetails",
			Handler:    _ABitOfEverythingService_ErrorWithDetails_Handler,
		},
		{
			MethodName: "GetMessageWithBody",
			Handler:    _ABitOfEverythingService_GetMessageWithBody_Handler,
		},
		{
			MethodName: "PostWithEmptyBody",
			Handler:    _ABitOfEverythingService_PostWithEmptyBody_Handler,
		},
		{
			MethodName: "GetWithMimicObjectResponse",
			Handler:    _ABitOfEverythingService_GetWithMimicObjectResponse_Handler,
		},
		{
			MethodName: "PostWithMimicObjectRequest",
			Handler:    _ABitOfEverythingService_PostWithMimicObjectRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/proto/examplepb/a_bit_of_everything.proto",
}

// CamelCaseServiceNameClient is the client API for CamelCaseServiceName service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CamelCaseServiceNameClient interface {
	Empty(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type camelCaseServiceNameClient struct {
	cc *grpc.ClientConn
}

func NewCamelCaseServiceNameClient(cc *grpc.ClientConn) CamelCaseServiceNameClient {
	return &camelCaseServiceNameClient{cc}
}

func (c *camelCaseServiceNameClient) Empty(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.camelCaseServiceName/Empty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CamelCaseServiceNameServer is the server API for CamelCaseServiceName service.
type CamelCaseServiceNameServer interface {
	Empty(context.Context, *empty.Empty) (*empty.Empty, error)
}

func RegisterCamelCaseServiceNameServer(s *grpc.Server, srv CamelCaseServiceNameServer) {
	s.RegisterService(&_CamelCaseServiceName_serviceDesc, srv)
}

func _CamelCaseServiceName_Empty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CamelCaseServiceNameServer).Empty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.camelCaseServiceName/Empty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CamelCaseServiceNameServer).Empty(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _CamelCaseServiceName_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gateway.examples.examplepb.camelCaseServiceName",
	HandlerType: (*CamelCaseServiceNameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Empty",
			Handler:    _CamelCaseServiceName_Empty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/proto/examplepb/a_bit_of_everything.proto",
}

// AnotherServiceWithNoBindingsClient is the client API for AnotherServiceWithNoBindings service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnotherServiceWithNoBindingsClient interface {
	NoBindings(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type anotherServiceWithNoBindingsClient struct {
	cc *grpc.ClientConn
}

func NewAnotherServiceWithNoBindingsClient(cc *grpc.ClientConn) AnotherServiceWithNoBindingsClient {
	return &anotherServiceWithNoBindingsClient{cc}
}

func (c *anotherServiceWithNoBindingsClient) NoBindings(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.gateway.examples.examplepb.AnotherServiceWithNoBindings/NoBindings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnotherServiceWithNoBindingsServer is the server API for AnotherServiceWithNoBindings service.
type AnotherServiceWithNoBindingsServer interface {
	NoBindings(context.Context, *empty.Empty) (*empty.Empty, error)
}

func RegisterAnotherServiceWithNoBindingsServer(s *grpc.Server, srv AnotherServiceWithNoBindingsServer) {
	s.RegisterService(&_AnotherServiceWithNoBindings_serviceDesc, srv)
}

func _AnotherServiceWithNoBindings_NoBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnotherServiceWithNoBindingsServer).NoBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gateway.examples.examplepb.AnotherServiceWithNoBindings/NoBindings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnotherServiceWithNoBindingsServer).NoBindings(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AnotherServiceWithNoBindings_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gateway.examples.examplepb.AnotherServiceWithNoBindings",
	HandlerType: (*AnotherServiceWithNoBindingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NoBindings",
			Handler:    _AnotherServiceWithNoBindings_NoBindings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/proto/examplepb/a_bit_of_everything.proto",
}

func init() {
	proto.RegisterFile("examples/proto/examplepb/a_bit_of_everything.proto", fileDescriptor_a_bit_of_everything_a0cdfe3e1bdeb13b)
}

var fileDescriptor_a_bit_of_everything_a0cdfe3e1bdeb13b = []byte{
	// 2670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x59, 0xcf, 0x6f, 0x1b, 0xc7,
	0xf5, 0xd7, 0x92, 0x12, 0x2d, 0x3d, 0xfd, 0xa2, 0x46, 0x8e, 0x2d, 0x33, 0x4e, 0x34, 0x66, 0x9c,
	0x84, 0x51, 0xcc, 0x5d, 0x89, 0xd6, 0x37, 0xb0, 0xf5, 0x45, 0xbe, 0xfe, 0x52, 0x96, 0x6c, 0x2b,
	0x8e, 0x25, 0x79, 0xfd, 0x23, 0x81, 0x63, 0x47, 0x5d, 0x72, 0x87, 0xe4, 0xc6, 0xdc, 0x9d, 0xcd,
	0xce, 0xac, 0x64, 0x56, 0x55, 0x8b, 0xb4, 0x40, 0x8b, 0xb6, 0x87, 0x02, 0xea, 0x2d, 0x87, 0xa0,
	0x40, 0x81, 0xa2, 0x97, 0x02, 0xbd, 0xf4, 0xd4, 0x43, 0xd1, 0x43, 0x4e, 0xb9, 0x35, 0x40, 0x0f,
	0xbd, 0xb6, 0x87, 0xf6, 0xde, 0x3f, 0xa0, 0x98, 0xd9, 0x1f, 0x5a, 0x92, 0x62, 0x68, 0xca, 0x45,
	0x2e, 0x16, 0x67, 0xe6, 0x33, 0xef, 0xbd, 0xf9, 0xbc, 0x79, 0x6f, 0xde, 0x5b, 0x43, 0x89, 0x3c,
	0x33, 0x6c, 0xb7, 0x49, 0x98, 0xe6, 0x7a, 0x94, 0x53, 0x2d, 0x1c, 0xba, 0x15, 0xcd, 0xd8, 0xa9,
	0x58, 0x7c, 0x87, 0xd6, 0x76, 0xc8, 0x2e, 0xf1, 0x5a, 0xbc, 0x61, 0x39, 0x75, 0x55, 0x62, 0xd0,
	0x7c, 0xdd, 0x73, 0xab, 0x6a, 0xdd, 0xe0, 0x64, 0xcf, 0x68, 0xa9, 0x91, 0x00, 0x35, 0xde, 0x9a,
	0x3b, 0x5f, 0xa7, 0xb4, 0xde, 0x24, 0x9a, 0xe1, 0x5a, 0x9a, 0xe1, 0x38, 0x94, 0x1b, 0xdc, 0xa2,
	0x0e, 0x0b, 0xb6, 0xe7, 0x5e, 0x0e, 0x57, 0xe5, 0xa8, 0xe2, 0xd7, 0x34, 0x62, 0xbb, 0xbc, 0x15,
	0x2e, 0xbe, 0xda, 0xb9, 0x68, 0xfa, 0x9e, 0xdc, 0x1d, 0xae, 0xe3, 0x0e, 0x7b, 0x99, 0x5f, 0xd1,
	0x6c, 0xc2, 0x98, 0x51, 0x27, 0x21, 0xe2, 0x42, 0x37, 0xa2, 0xd4, 0x01, 0x99, 0xef, 0x54, 0xc2,
	0x2d, 0x9b, 0x30, 0x6e, 0xd8, 0x6e, 0x08, 0xb8, 0x24, 0xff, 0x54, 0x8b, 0x75, 0xe2, 0x14, 0xd9,
	0x9e, 0x51, 0xaf, 0x13, 0x4f, 0xa3, 0xae, 0x3c, 0x44, 0xf7, 0x81, 0xf2, 0x5f, 0x23, 0xc8, 0x96,
	0x57, 0x2d, 0xbe, 0x55, 0x5b, 0x8f, 0xa9, 0x42, 0x4f, 0x60, 0x92, 0x59, 0x4e, 0xbd, 0x49, 0x76,
	0x1c, 0xc2, 0x38, 0x31, 0xe7, 0xce, 0x61, 0xa5, 0x30, 0x5e, 0xba, 0xa2, 0xf6, 0x21, 0x4f, 0xed,
	0x94, 0xa4, 0x6e, 0xca, 0xfd, 0xfa, 0x44, 0x20, 0x2e, 0x18, 0x21, 0x02, 0xc3, 0xbe, 0x6f, 0x99,
	0x73, 0x0a, 0x56, 0x0a, 0x63, 0xab, 0x77, 0x0f, 0xcb, 0x9b, 0x3f, 0x53, 0x6e, 0x7f, 0x64, 0x14,
	0x6b, 0xe5, 0xe2, 0x8d, 0xc5, 0xe2, 0xd5, 0x27, 0xfb, 0x57, 0x0e, 0x8a, 0xc9, 0xe1, 0xf2, 0x20,
	0xc3, 0xa5, 0xd2, 0x81, 0x2e, 0xc5, 0xa3, 0x6d, 0xc8, 0x84, 0xe6, 0xa7, 0x70, 0xfa, 0x85, 0xcc,
	0x0f, 0xe5, 0xa0, 0x79, 0x18, 0xaf, 0x35, 0xa9, 0xc1, 0x77, 0x76, 0x8d, 0xa6, 0x4f, 0xe6, 0xd2,
	0x58, 0x29, 0xa4, 0x74, 0x90, 0x53, 0x0f, 0xc5, 0x0c, 0xba, 0x00, 0x13, 0x26, 0xf5, 0x2b, 0x4d,
	0x12, 0x22, 0x86, 0xb1, 0x52, 0x50, 0xf4, 0xf1, 0x60, 0x2e, 0x80, 0xcc, 0xc3, 0xb8, 0xe5, 0xf0,
	0x77, 0x96, 0x43, 0xc4, 0x08, 0x56, 0x0a, 0x69, 0x1d, 0xe4, 0x54, 0x2c, 0xc3, 0x4f, 0x22, 0x32,
	0x58, 0x29, 0x0c, 0xeb, 0xe3, 0x7e, 0x02, 0x12, 0xc8, 0xb8, 0x5c, 0x0a, 0x11, 0xa7, 0xb0, 0x52,
	0x18, 0x91, 0x32, 0x2e, 0x97, 0x02, 0xc0, 0x6b, 0x30, 0x59, 0xb3, 0x9e, 0x11, 0x33, 0x16, 0x32,
	0x8a, 0x95, 0x42, 0x46, 0x9f, 0x08, 0x27, 0xdb, 0x41, 0xb1, 0x9c, 0x31, 0xac, 0x14, 0x4e, 0x85,
	0xa0, 0x48, 0xd2, 0x2b, 0x00, 0x15, 0x4a, 0x9b, 0x21, 0x02, 0xb0, 0x52, 0x18, 0xd5, 0xc7, 0xc4,
	0x4c, 0x6c, 0x2c, 0xe3, 0x9e, 0xe5, 0xd4, 0x43, 0xc0, 0xb8, 0x70, 0xa9, 0x3e, 0x1e, 0xcc, 0xc5,
	0xc6, 0x56, 0x5a, 0x9c, 0xb0, 0x10, 0xf1, 0x0a, 0x56, 0x0a, 0x13, 0x3a, 0xc8, 0xa9, 0xb6, 0x03,
	0xc7, 0x66, 0x4c, 0x62, 0xa5, 0x30, 0x19, 0x1c, 0x38, 0xb2, 0xe2, 0x36, 0x00, 0x71, 0x7c, 0x3b,
	0x04, 0x4c, 0x61, 0xa5, 0x30, 0x55, 0xba, 0xd4, 0xd7, 0x9d, 0x9b, 0xbe, 0x4d, 0x3c, 0xab, 0xba,
	0xee, 0xf8, 0xb6, 0x3e, 0x26, 0xf6, 0x07, 0xc2, 0x5e, 0x87, 0x29, 0xd6, 0x7e, 0xf0, 0x69, 0xac,
	0x14, 0xa6, 0xf5, 0x49, 0xd6, 0x76, 0xf2, 0x18, 0x16, 0x93, 0x98, 0xc5, 0x4a, 0x21, 0x1b, 0xc1,
	0x12, 0xee, 0x62, 0x49, 0xeb, 0x67, 0xb0, 0x52, 0x98, 0xd1, 0xc7, 0x59, 0xc2, 0xfa, 0x10, 0x12,
	0xcb, 0x41, 0x58, 0x29, 0xa0, 0x00, 0x12, 0x49, 0x29, 0xc1, 0x4b, 0x1e, 0x71, 0x89, 0xc1, 0x89,
	0xb9, 0xd3, 0x46, 0xe8, 0x2c, 0x4e, 0x17, 0xc6, 0xf4, 0xd9, 0x68, 0xf1, 0x5e, 0x82, 0xd8, 0xab,
	0x30, 0x4e, 0x1d, 0x22, 0x92, 0x9c, 0xc8, 0x41, 0x73, 0xa7, 0x65, 0x8c, 0x9e, 0x51, 0x83, 0xfc,
	0xa0, 0x46, 0xf9, 0x41, 0x5d, 0x17, 0xab, 0xb7, 0x86, 0x74, 0x90, 0x60, 0x39, 0x42, 0xaf, 0xc1,
	0x44, 0xb0, 0x35, 0xd0, 0x35, 0xf7, 0x92, 0x70, 0xdb, 0xad, 0x21, 0x3d, 0x10, 0x18, 0x28, 0x41,
	0x8f, 0x61, 0xcc, 0x36, 0xdc, 0xd0, 0x8e, 0x33, 0x32, 0x84, 0xae, 0x0d, 0x1e, 0x42, 0x77, 0x0c,
	0x57, 0x9a, 0xbb, 0xee, 0x70, 0xaf, 0xa5, 0x8f, 0xda, 0xe1, 0x10, 0x3d, 0x83, 0x59, 0xdb, 0x70,
	0xdd, 0xce, 0xf3, 0x9e, 0x95, 0x7a, 0x6e, 0x9d, 0x48, 0x8f, 0xdb, 0xc6, 0x4f, 0xa0, 0x70, 0xc6,
	0xee, 0x9c, 0x4f, 0x68, 0x0e, 0xc2, 0x3a, 0xd4, 0x3c, 0xf7, 0x62, 0x9a, 0x83, 0x54, 0xd1, 0xad,
	0x39, 0x31, 0x8f, 0x56, 0x60, 0xce, 0xa1, 0xce, 0x75, 0xea, 0xec, 0x12, 0x47, 0x24, 0x61, 0xa3,
	0xb9, 0x69, 0xd8, 0x41, 0x5e, 0x98, 0xcb, 0xc9, 0xc8, 0xe9, 0xb9, 0x8e, 0xae, 0xc3, 0x74, 0x9c,
	0xe9, 0x43, 0x8b, 0x5f, 0x96, 0x1e, 0xcf, 0x75, 0x79, 0xfc, 0x7e, 0x84, 0xd3, 0xa7, 0xe2, 0x2d,
	0x81, 0x90, 0xc7, 0x10, 0xdf, 0xa4, 0x9d, 0x44, 0x40, 0x9d, 0xc7, 0xe9, 0x81, 0x03, 0x6a, 0x26,
	0x12, 0xb4, 0x1e, 0x07, 0xd6, 0x03, 0x98, 0xb0, 0x2d, 0xdb, 0xaa, 0x46, 0xb7, 0xea, 0x55, 0x69,
	0x5f, 0xa9, 0xaf, 0xd8, 0x3b, 0x62, 0xd3, 0x56, 0xe5, 0x13, 0x52, 0xe5, 0xb7, 0x2c, 0xd3, 0x24,
	0x8e, 0x3e, 0x2e, 0xe5, 0x04, 0x4e, 0xcb, 0xfd, 0x56, 0x81, 0x4c, 0xf8, 0x72, 0x20, 0x18, 0x76,
	0x0c, 0x9b, 0x04, 0x2f, 0x87, 0x2e, 0x7f, 0xa3, 0x33, 0x90, 0x31, 0x6c, 0xea, 0x3b, 0x7c, 0x2e,
	0x25, 0x13, 0x47, 0x38, 0x42, 0x77, 0x21, 0x45, 0x9f, 0xca, 0x1c, 0x3d, 0x55, 0x2a, 0x9f, 0x34,
	0xf5, 0xab, 0x6b, 0x84, 0xb8, 0xf2, 0xbc, 0x29, 0xfa, 0x34, 0x3f, 0x0f, 0xa3, 0xd1, 0x18, 0x8d,
	0xc1, 0xc8, 0x8d, 0xf2, 0xfb, 0xf7, 0xd6, 0xb3, 0x43, 0x68, 0x14, 0x86, 0xef, 0xeb, 0x0f, 0xd6,
	0xb3, 0x4a, 0xce, 0x82, 0xc9, 0xb6, 0xfb, 0x8e, 0xb2, 0x90, 0x7e, 0x4a, 0x5a, 0xa1, 0xbd, 0xe2,
	0x27, 0x5a, 0x85, 0x91, 0x80, 0xf4, 0xd4, 0x09, 0xb2, 0x58, 0xb0, 0x75, 0x25, 0x75, 0x45, 0xc9,
	0xad, 0xc1, 0x99, 0xe3, 0xaf, 0xfc, 0x31, 0x3a, 0x4f, 0x27, 0x75, 0x8e, 0x25, 0xa5, 0x7c, 0x3f,
	0x92, 0xd2, 0x79, 0x7d, 0x8f, 0x91, 0xb2, 0x99, 0x94, 0xf2, 0x22, 0xcf, 0xe9, 0x91, 0xfe, 0x95,
	0x2f, 0x95, 0xc3, 0xf2, 0x9f, 0x15, 0xa8, 0x2f, 0xcc, 0x96, 0x71, 0xc5, 0xe2, 0x98, 0xd6, 0xf0,
	0x51, 0xc9, 0x56, 0xda, 0xd8, 0x70, 0x78, 0x14, 0x09, 0x2d, 0x5c, 0xa5, 0xb6, 0xdb, 0xb4, 0xaa,
	0xe2, 0xce, 0xe1, 0xb0, 0x26, 0xc2, 0xbc, 0xe5, 0x12, 0xcc, 0x29, 0xae, 0xd2, 0x5d, 0xe2, 0x61,
	0xdb, 0x70, 0x5a, 0xb8, 0x46, 0x0c, 0xee, 0x7b, 0x84, 0x09, 0x59, 0xdb, 0x51, 0x48, 0xfc, 0x45,
	0x91, 0x35, 0xc1, 0xc2, 0x43, 0xb8, 0x78, 0xc3, 0x72, 0x4c, 0x4c, 0x7d, 0x8e, 0x6d, 0xea, 0x11,
	0x6c, 0x54, 0xc4, 0xcf, 0xae, 0x0a, 0x48, 0x6d, 0x70, 0xee, 0xb2, 0x15, 0x4d, 0xab, 0x5b, 0xbc,
	0xe1, 0x57, 0xd4, 0x2a, 0xb5, 0x35, 0x71, 0xdc, 0x22, 0xa9, 0x52, 0xd6, 0x62, 0x9c, 0x84, 0xc3,
	0xf0, 0xf4, 0xab, 0x93, 0x51, 0x2e, 0x96, 0x47, 0xcb, 0xe7, 0x60, 0x78, 0x95, 0x9a, 0xad, 0xe3,
	0xee, 0x6b, 0xfe, 0x31, 0x4c, 0xdf, 0x09, 0xac, 0xff, 0xc0, 0xe2, 0x0d, 0x09, 0x9b, 0x82, 0x54,
	0x54, 0x0e, 0xe9, 0x29, 0xcb, 0x44, 0x57, 0x61, 0xd8, 0x34, 0xb8, 0x11, 0x12, 0xfd, 0x7a, 0x5f,
	0xa2, 0x85, 0x10, 0x5d, 0x6e, 0xc9, 0xff, 0x3b, 0x05, 0xb3, 0x89, 0x78, 0xd2, 0x09, 0x73, 0xa9,
	0xc3, 0x08, 0xba, 0x04, 0xc8, 0x0b, 0x7f, 0x07, 0x36, 0xee, 0x50, 0x27, 0xb2, 0x2b, 0x1b, 0xad,
	0x48, 0xf7, 0x6f, 0x39, 0xc7, 0xa1, 0xf9, 0x1e, 0x0d, 0x6f, 0x4f, 0x3b, 0xfa, 0xfe, 0x1e, 0x45,
	0x4f, 0x61, 0x32, 0x46, 0x8b, 0xac, 0x12, 0x06, 0xdd, 0x8d, 0x41, 0x02, 0x3f, 0x32, 0x34, 0x98,
	0x8b, 0x46, 0xf2, 0xd2, 0x4f, 0x78, 0x89, 0x51, 0x7e, 0x09, 0x66, 0xba, 0x20, 0x68, 0x12, 0xc6,
	0x1e, 0x96, 0xdf, 0x7f, 0xb0, 0xbe, 0xb3, 0xb5, 0x29, 0x02, 0x32, 0x1e, 0xde, 0xff, 0x60, 0x2b,
	0xab, 0xac, 0x18, 0x87, 0xe5, 0x8f, 0xe1, 0x71, 0xe9, 0x21, 0x6f, 0x58, 0x2c, 0xbe, 0x39, 0x32,
	0xc3, 0x30, 0x1c, 0xa4, 0x2a, 0x79, 0x8f, 0x2e, 0xe1, 0x06, 0xdd, 0x13, 0xb7, 0x0f, 0xef, 0x35,
	0x88, 0x83, 0x5d, 0x9f, 0x63, 0xcb, 0xc1, 0x91, 0x72, 0xec, 0x11, 0xc7, 0x24, 0x1e, 0x31, 0xb1,
	0xc1, 0xb0, 0x81, 0x4d, 0x52, 0xb3, 0x1c, 0x4b, 0x5c, 0xcd, 0xcf, 0x53, 0xca, 0xa9, 0xfc, 0xbf,
	0x52, 0x80, 0xda, 0x4e, 0xf3, 0xa9, 0x4f, 0x18, 0x47, 0x0b, 0x30, 0xe3, 0x05, 0x3f, 0xbb, 0x48,
	0x9f, 0x0e, 0x17, 0x62, 0xce, 0xbb, 0xb0, 0x47, 0x94, 0xb7, 0x61, 0x05, 0xe3, 0x75, 0x98, 0x88,
	0xb0, 0x09, 0xc2, 0xd7, 0x06, 0x23, 0x5c, 0xee, 0x8f, 0xf8, 0x96, 0x03, 0x49, 0xf7, 0xb8, 0x77,
	0x34, 0xc8, 0x2f, 0x42, 0xb6, 0x13, 0xd0, 0x87, 0xec, 0xef, 0x1c, 0x96, 0x9f, 0xc0, 0x47, 0xa5,
	0x07, 0x27, 0x24, 0x5b, 0xaa, 0xf9, 0x66, 0xae, 0x7f, 0x95, 0x0a, 0xaf, 0x40, 0xf2, 0xc9, 0x40,
	0x05, 0xc8, 0x36, 0xe4, 0xaf, 0x2e, 0xa6, 0xa7, 0x82, 0xf9, 0x98, 0xe8, 0x4e, 0xe4, 0x11, 0xcf,
	0x49, 0xa4, 0xa0, 0xf9, 0x63, 0x18, 0x0f, 0x91, 0x09, 0x96, 0xdf, 0x1d, 0xfc, 0x3d, 0x53, 0x83,
	0x3f, 0x92, 0x5e, 0x68, 0xc4, 0xbf, 0xf3, 0x0b, 0x00, 0x47, 0x2b, 0x7d, 0x78, 0x7d, 0xfb, 0xb0,
	0x5c, 0x80, 0x37, 0x4a, 0xb8, 0x0f, 0xaf, 0xaa, 0xa0, 0x68, 0x01, 0xc3, 0x78, 0xe2, 0xd9, 0x10,
	0x0f, 0xd4, 0xa3, 0x75, 0x7d, 0x2b, 0x3b, 0x84, 0x4e, 0x41, 0x5a, 0x48, 0x57, 0x4a, 0x9f, 0x9d,
	0x85, 0xb3, 0x9d, 0x59, 0xef, 0x1e, 0xf1, 0x76, 0xad, 0x2a, 0x41, 0x5f, 0xa4, 0x21, 0x73, 0xdd,
	0x13, 0x8f, 0x3b, 0x5a, 0x1a, 0x38, 0xc9, 0xe7, 0x06, 0xdf, 0x92, 0xff, 0x5d, 0xea, 0x87, 0x5f,
	0xff, 0xe3, 0x97, 0xa9, 0xdf, 0xa4, 0xf2, 0xbf, 0x4e, 0x69, 0xbb, 0x4b, 0x51, 0x23, 0x7f, 0x5c,
	0x1b, 0xaf, 0xed, 0x27, 0x3a, 0xb0, 0x03, 0x6d, 0x3f, 0xd9, 0x6e, 0x1d, 0x68, 0xfb, 0x89, 0x32,
	0xfb, 0x40, 0x63, 0xc4, 0x35, 0x3c, 0x83, 0x53, 0x4f, 0xdb, 0xf7, 0xdb, 0x16, 0xf6, 0x13, 0x05,
	0xfb, 0x81, 0xb6, 0xdf, 0x56, 0xe5, 0x47, 0xe3, 0xc4, 0xfa, 0x51, 0x03, 0x74, 0xa0, 0xed, 0x27,
	0xab, 0xd5, 0x77, 0x19, 0xf7, 0x5c, 0x8f, 0xd4, 0xac, 0x67, 0xda, 0xc2, 0x41, 0xa0, 0x24, 0xb1,
	0x8d, 0x75, 0xca, 0x61, 0x9d, 0x8a, 0x58, 0xc7, 0x86, 0x76, 0x23, 0x7b, 0x95, 0x82, 0x07, 0xe8,
	0x0b, 0x05, 0x20, 0x70, 0x90, 0x7c, 0x3e, 0xbe, 0x1d, 0x27, 0x2d, 0x48, 0x1f, 0x5d, 0xcc, 0xcf,
	0xf7, 0xf1, 0xd0, 0x8a, 0xb2, 0x80, 0xbe, 0x07, 0x99, 0xf7, 0x29, 0x7d, 0xea, 0xbb, 0x68, 0x5a,
	0x65, 0x7e, 0xa5, 0xa4, 0x6e, 0x98, 0xe1, 0x9b, 0x77, 0x12, 0xcd, 0xaa, 0xd4, 0x5c, 0x40, 0x6f,
	0xf4, 0xbd, 0x1b, 0xe2, 0x8d, 0x3f, 0x40, 0x3f, 0x56, 0x20, 0xf3, 0xc0, 0x35, 0x4f, 0x78, 0x7f,
	0x7b, 0x74, 0x50, 0xf9, 0x25, 0x69, 0xc5, 0xdb, 0xb9, 0xe7, 0xb4, 0x42, 0xd0, 0xf0, 0x0b, 0x05,
	0x32, 0x6b, 0xa4, 0x49, 0x38, 0xe9, 0xe6, 0xa1, 0x97, 0x9a, 0xc7, 0x87, 0xe5, 0xb7, 0x2b, 0x6f,
	0xc1, 0x14, 0x40, 0xd9, 0xb5, 0x6e, 0x93, 0x56, 0xd9, 0xe7, 0x0d, 0x34, 0x04, 0x67, 0x21, 0xb3,
	0x25, 0x7e, 0x96, 0xd0, 0x24, 0x0c, 0x7b, 0xc4, 0x30, 0x61, 0x64, 0xcf, 0xb3, 0x38, 0x09, 0xa8,
	0x59, 0x78, 0x5e, 0x6a, 0xfe, 0xae, 0xc0, 0xe8, 0x4d, 0xc2, 0xef, 0xfa, 0xc4, 0x6b, 0xfd, 0x37,
	0xc9, 0xf9, 0xb9, 0x72, 0x58, 0xbe, 0x9f, 0xdf, 0x84, 0xf3, 0xc7, 0x55, 0x57, 0xb1, 0xc2, 0x01,
	0xab, 0xaa, 0x0f, 0x95, 0xca, 0x90, 0x3c, 0x9f, 0x8a, 0x2e, 0xf5, 0x3b, 0xdf, 0xa7, 0x42, 0x41,
	0x74, 0xca, 0x2f, 0xd3, 0x30, 0xbc, 0x5e, 0x6d, 0x50, 0x54, 0xe8, 0x71, 0x42, 0xe6, 0x57, 0xd4,
	0xa0, 0x6e, 0x8e, 0xdc, 0xf1, 0xdc, 0xc8, 0xfc, 0x3f, 0x53, 0x87, 0xe5, 0xcf, 0x52, 0x30, 0x41,
	0xaa, 0x0d, 0x8a, 0x59, 0x90, 0x32, 0x61, 0x54, 0x8e, 0x3c, 0xb7, 0x8a, 0x66, 0xee, 0xf9, 0xb6,
	0x6d, 0x78, 0xad, 0x15, 0xbc, 0x1e, 0x4e, 0xe5, 0xb2, 0x6b, 0x84, 0x55, 0x3d, 0x4b, 0x7e, 0x83,
	0x93, 0xb3, 0xf9, 0x35, 0x40, 0xed, 0x44, 0x49, 0x6b, 0x07, 0xa4, 0xe7, 0xbd, 0x6b, 0x90, 0xfe,
	0x9f, 0xc5, 0xcb, 0xe8, 0x0a, 0xbc, 0xa3, 0x13, 0xee, 0x7b, 0x0e, 0x31, 0x83, 0xc7, 0x94, 0x37,
	0x44, 0xb5, 0xc2, 0xa8, 0xef, 0x55, 0x09, 0xb6, 0x18, 0xe6, 0xc4, 0x76, 0xa9, 0x67, 0x78, 0x56,
	0xb3, 0x85, 0x7d, 0xc7, 0xd8, 0x35, 0xac, 0xa6, 0x51, 0x69, 0x12, 0xf5, 0xbd, 0xff, 0x85, 0xf4,
	0xf2, 0xe2, 0x32, 0x5a, 0x86, 0x85, 0x6f, 0x10, 0x60, 0x52, 0xc2, 0xb0, 0x43, 0x39, 0x26, 0xcf,
	0x2c, 0xc6, 0x55, 0x94, 0x81, 0xe1, 0xcf, 0x53, 0x4a, 0x5a, 0x3a, 0xe6, 0x49, 0x7f, 0xc7, 0x08,
	0x62, 0xb4, 0xfd, 0x20, 0xa7, 0x3d, 0x3a, 0x97, 0xcf, 0x6a, 0xbb, 0xa5, 0x18, 0x2f, 0xd6, 0x56,
	0x82, 0x6e, 0xe0, 0x11, 0x42, 0x5d, 0x4b, 0xe8, 0x0f, 0x0a, 0x4c, 0x88, 0x86, 0x6b, 0xdb, 0xe0,
	0x0d, 0xc9, 0xd0, 0xb7, 0x93, 0xe9, 0xae, 0xc9, 0xb3, 0x5d, 0xcd, 0x2f, 0xf7, 0x0d, 0xaa, 0xb6,
	0xaf, 0xa4, 0xaa, 0x28, 0xef, 0x65, 0xdc, 0x97, 0x01, 0x36, 0xe9, 0xaa, 0xe5, 0x98, 0x96, 0x53,
	0x67, 0xe8, 0x5c, 0x57, 0xcc, 0xac, 0x85, 0xdf, 0x85, 0x7b, 0x86, 0xd3, 0x10, 0x7a, 0x08, 0xa7,
	0x44, 0x1b, 0x4f, 0x7d, 0x8e, 0x7a, 0x80, 0x7a, 0x6e, 0x7e, 0x59, 0x9a, 0xff, 0x12, 0x9a, 0x4d,
	0xf2, 0xc9, 0x43, 0x61, 0x0d, 0xc8, 0xae, 0x7b, 0x1e, 0xf5, 0x44, 0xef, 0xb1, 0x46, 0xb8, 0x61,
	0x35, 0xd9, 0xc0, 0x0a, 0x2e, 0x4a, 0x05, 0xaf, 0xa2, 0xf3, 0x6d, 0x0e, 0x13, 0x52, 0xf7, 0x2c,
	0xde, 0x30, 0x43, 0xa9, 0x3f, 0x51, 0x00, 0xdd, 0x24, 0xbc, 0xb3, 0xd7, 0x59, 0xec, 0x5f, 0x3e,
	0xb5, 0xef, 0xe8, 0x69, 0xc6, 0x9b, 0xd2, 0x8c, 0x0b, 0xf9, 0x73, 0x49, 0x33, 0x84, 0x05, 0x15,
	0x6a, 0xb6, 0xb4, 0x7d, 0x91, 0x83, 0x65, 0x4f, 0x84, 0x7e, 0xa4, 0xc0, 0xcc, 0x36, 0x65, 0x5c,
	0x48, 0x94, 0x5b, 0xa5, 0x21, 0xcf, 0xd7, 0x56, 0xf5, 0xd4, 0xae, 0x49, 0xed, 0x6f, 0xe5, 0x2f,
	0x26, 0xb5, 0xbb, 0x94, 0x71, 0x61, 0x81, 0xfc, 0x22, 0x17, 0x98, 0x11, 0x5f, 0x8a, 0xcf, 0x15,
	0xc8, 0xdd, 0x24, 0xd2, 0x88, 0xe3, 0x1a, 0xb4, 0x5e, 0x4e, 0x58, 0x3e, 0x49, 0x17, 0x95, 0x7c,
	0x32, 0x8f, 0xac, 0xab, 0x13, 0x69, 0x9c, 0x2c, 0x1a, 0xa9, 0xc4, 0x47, 0xcd, 0x0d, 0xfa, 0xbd,
	0x02, 0xb9, 0x88, 0xa2, 0x63, 0xfa, 0x98, 0xcb, 0x27, 0xe8, 0x2c, 0x7a, 0x32, 0xb7, 0x2e, 0x6d,
	0xbb, 0x96, 0x5f, 0x39, 0x8e, 0xb9, 0x36, 0xe3, 0xa4, 0x1c, 0x6d, 0xbf, 0xab, 0x85, 0x12, 0x7c,
	0xe6, 0xfe, 0xa4, 0x1c, 0x96, 0xff, 0xa8, 0xa0, 0x5a, 0x8f, 0x2a, 0x16, 0x9b, 0x89, 0xa4, 0x5b,
	0x2c, 0xe2, 0xbd, 0x86, 0x55, 0x6d, 0x60, 0xd6, 0xa0, 0x7e, 0xd3, 0x94, 0xe9, 0xac, 0x42, 0xb0,
	0xcf, 0x88, 0x29, 0xda, 0x0e, 0xb7, 0x69, 0x54, 0x09, 0xa6, 0x35, 0x99, 0xf8, 0x4c, 0x5a, 0xf5,
	0x6d, 0xe2, 0x04, 0xff, 0x4d, 0x82, 0xab, 0xd4, 0x16, 0x83, 0x0b, 0xb9, 0xbb, 0x30, 0x7f, 0xdc,
	0xdb, 0x26, 0xd2, 0x52, 0x54, 0x37, 0x0f, 0x98, 0xbf, 0x4b, 0x9f, 0xc0, 0xe9, 0xaa, 0x61, 0x93,
	0xe6, 0x75, 0x83, 0x91, 0x50, 0x86, 0x28, 0xf2, 0x90, 0x0e, 0x23, 0xc1, 0x67, 0xda, 0x41, 0x03,
	0xf3, 0x9c, 0x64, 0x76, 0x16, 0xcd, 0xb4, 0x05, 0xa6, 0x58, 0x2a, 0x7d, 0x0c, 0xe7, 0xcb, 0x0e,
	0xe5, 0x0d, 0xe2, 0x85, 0x9a, 0x84, 0xa7, 0x13, 0x49, 0xea, 0xff, 0xda, 0x52, 0xd6, 0xa0, 0x8a,
	0x87, 0x56, 0xff, 0x96, 0x39, 0x2c, 0x7f, 0x95, 0x41, 0x1c, 0x66, 0xcb, 0x78, 0x35, 0xf8, 0x90,
	0x93, 0xc8, 0xa8, 0x1f, 0xc2, 0xe9, 0xba, 0xbe, 0x7d, 0xbd, 0x78, 0x33, 0x38, 0x39, 0x76, 0x3d,
	0x2a, 0x3c, 0x3c, 0x28, 0x63, 0xb9, 0xac, 0x43, 0x1d, 0xf2, 0xff, 0xe1, 0xc9, 0x04, 0xba, 0x94,
	0x5e, 0x52, 0x17, 0x17, 0xd2, 0x4a, 0x6a, 0xb8, 0x94, 0x35, 0xdc, 0xe0, 0xf3, 0x90, 0x45, 0x1d,
	0xed, 0x13, 0x46, 0x9d, 0xd2, 0x99, 0xe4, 0xcc, 0xb3, 0x62, 0x8d, 0xd2, 0xa2, 0x6d, 0xd9, 0x64,
	0xa5, 0x0b, 0xb9, 0xd2, 0x03, 0xa9, 0x6f, 0x8b, 0x07, 0xf2, 0x32, 0xda, 0x80, 0x9b, 0xdd, 0x0f,
	0xa4, 0xcf, 0x88, 0x77, 0xf4, 0x38, 0x36, 0x8c, 0x5d, 0x82, 0x5d, 0xe2, 0xd9, 0x16, 0x63, 0xe2,
	0xde, 0x70, 0x8a, 0x8d, 0x6a, 0x95, 0x30, 0xd6, 0xf6, 0x98, 0xaa, 0xfa, 0x0b, 0x3c, 0xb9, 0xa7,
	0xf4, 0x5b, 0x90, 0x5e, 0x5e, 0xba, 0x82, 0xca, 0x30, 0xb9, 0xf1, 0xa6, 0x8d, 0x0d, 0xcc, 0x89,
	0xe1, 0x52, 0xae, 0xa2, 0x45, 0x50, 0x73, 0x03, 0x7d, 0x48, 0x7c, 0xf4, 0xd3, 0x14, 0x4c, 0xc3,
	0xd8, 0xaa, 0xc1, 0xac, 0xaa, 0x2c, 0x30, 0x53, 0xa3, 0x0a, 0xbc, 0xd2, 0x56, 0x72, 0x4e, 0x8f,
	0xa6, 0x72, 0x63, 0x1f, 0x16, 0xcb, 0xdb, 0x1b, 0xc5, 0xdb, 0xa4, 0x85, 0x53, 0xf0, 0x57, 0x25,
	0x2e, 0x41, 0xbf, 0x52, 0x46, 0xd3, 0x85, 0xe1, 0xd2, 0x6b, 0x91, 0xf7, 0x12, 0x0e, 0xd1, 0xa8,
	0xe1, 0xf3, 0x86, 0x26, 0xfe, 0xa1, 0x9e, 0xf5, 0x5d, 0xb2, 0x32, 0xdf, 0x1b, 0xc4, 0xe9, 0x53,
	0xe2, 0xac, 0xfe, 0x00, 0x72, 0x41, 0x45, 0x8b, 0xd0, 0x4d, 0xcf, 0x70, 0x38, 0xc3, 0x62, 0x10,
	0xb2, 0x07, 0xe7, 0xc3, 0x3a, 0x17, 0xcd, 0x86, 0x8b, 0x72, 0x14, 0xad, 0x5e, 0x87, 0x11, 0xc3,
	0xb4, 0x2d, 0x07, 0xad, 0xb4, 0x6d, 0x75, 0xcc, 0x36, 0x98, 0x74, 0x86, 0x80, 0x59, 0x8c, 0x8b,
	0x87, 0x77, 0x97, 0x60, 0xcb, 0xa9, 0x51, 0xcf, 0x96, 0xfe, 0xae, 0xcc, 0xc3, 0x64, 0x92, 0x8a,
	0xa1, 0xce, 0xda, 0xbb, 0xf2, 0x56, 0xcf, 0xea, 0xbb, 0x13, 0xea, 0x6d, 0xc0, 0xd9, 0x3b, 0x47,
	0xc9, 0x21, 0x79, 0xe7, 0x07, 0xbd, 0xeb, 0x8f, 0xc6, 0x62, 0xcf, 0x55, 0x32, 0x32, 0xdc, 0x2e,
	0xff, 0x27, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x11, 0xec, 0xc1, 0xf1, 0x1e, 0x00, 0x00,
}
