/*
 * A Bit of Everything
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package abe
import (
	"time"
)

// Intentionaly complicated message type to cover many features of Protobuf.
type ExamplepbABitOfEverything struct {
	BoolValue bool `json:"boolValue,omitempty"`
	BytesValue string `json:"bytesValue,omitempty"`
	DoubleValue float64 `json:"doubleValue"`
	EnumValue *ExamplepbNumericEnum `json:"enumValue,omitempty"`
	EnumValueAnnotation *ExamplepbNumericEnum `json:"enumValueAnnotation,omitempty"`
	Fixed32Value int64 `json:"fixed32Value,omitempty"`
	Fixed64Value string `json:"fixed64Value,omitempty"`
	// Float value field
	FloatValue float32 `json:"floatValue"`
	Int32Value int32 `json:"int32Value,omitempty"`
	Int64OverrideType int64 `json:"int64OverrideType,omitempty"`
	Int64Value string `json:"int64Value"`
	MapValue map[string]ExamplepbNumericEnum `json:"mapValue,omitempty"`
	MappedNestedValue map[string]ABitOfEverythingNested `json:"mappedNestedValue,omitempty"`
	MappedStringValue map[string]string `json:"mappedStringValue,omitempty"`
	Nested []ABitOfEverythingNested `json:"nested,omitempty"`
	NestedAnnotation *ABitOfEverythingNested `json:"nestedAnnotation,omitempty"`
	NestedPathEnumValue *MessagePathEnumNestedPathEnum `json:"nestedPathEnumValue,omitempty"`
	NonConventionalNameValue string `json:"nonConventionalNameValue,omitempty"`
	OneofEmpty *interface{} `json:"oneofEmpty,omitempty"`
	OneofString string `json:"oneofString,omitempty"`
	OptionalStringValue string `json:"optionalStringValue,omitempty"`
	OutputOnlyStringViaFieldBehaviorAnnotation string `json:"outputOnlyStringViaFieldBehaviorAnnotation,omitempty"`
	PathEnumValue *PathenumPathEnum `json:"pathEnumValue,omitempty"`
	// Repeated numeric enum description.
	RepeatedEnumAnnotation []ExamplepbNumericEnum `json:"repeatedEnumAnnotation,omitempty"`
	RepeatedEnumValue []ExamplepbNumericEnum `json:"repeatedEnumValue,omitempty"`
	// Repeated nested object description.
	RepeatedNestedAnnotation []ABitOfEverythingNested `json:"repeatedNestedAnnotation,omitempty"`
	// Repeated string description.
	RepeatedStringAnnotation []string `json:"repeatedStringAnnotation,omitempty"`
	RepeatedStringValue []string `json:"repeatedStringValue,omitempty"`
	RequiredStringViaFieldBehaviorAnnotation string `json:"requiredStringViaFieldBehaviorAnnotation"`
	Sfixed32Value int32 `json:"sfixed32Value,omitempty"`
	Sfixed64Value string `json:"sfixed64Value,omitempty"`
	SingleNested *ABitOfEverythingNested `json:"singleNested,omitempty"`
	Sint32Value int32 `json:"sint32Value,omitempty"`
	Sint64Value string `json:"sint64Value,omitempty"`
	StringValue string `json:"stringValue,omitempty"`
	TimestampValue time.Time `json:"timestampValue,omitempty"`
	Uint32Value int64 `json:"uint32Value,omitempty"`
	Uint64Value string `json:"uint64Value,omitempty"`
	Uuid string `json:"uuid"`
}
